### PR TITLE
Convert to ES modules

### PR DESCRIPTION
**Pull request by NMinhNguyen**
See https://github.com/facebook/react/pull/18145

# Test Plan

I've verified this locally and the build outputs aren't changed due to this. They're only slightly different due to the dependency updates.

### CODE REVIEW

**Comment by ljharb** [comment]
It’d be great to discuss major changes like this before making them; enzyme will need to use a shallow renderer that’s developed using the same standards enzyme itself is.

**Comment by NMinhNguyen** [comment]
@ljharb could you clarify why this would affect enzyme's usage of this package at all? I have verified the build outputs and there shouldn't be any difference, i.e. there's no need to do `require('react-shallow-renderer').default` if that's what you're worried about?

**Comment by gaearon** [comment]
Sorry we didn't communicate this clearly; this is mirroring the change we did in the React repo: https://github.com/facebook/react/pull/18145. It shouldn't affect the build in any meaningful way for the CJS mode.

**Comment by ljharb** [comment]
@gaearon ie the intention for Facebook to continue maintaining a parallel implementation, or will this become the canonical one?

**Comment by gaearon** [comment]
The plan is for this to be the canonical one.

**Pull request merged**
